GET http://localhost:8000/user

###
GET http://localhost:8000/user/abhinavkrish213@gmail.com

###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name": "Bobby Krishniah",
    "email": "pokemongoabhi@gmail.com",
    "image": "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18ya2lSUWNQMXVva2ZtNVExSHFreFc3OGUxMzAifQ?width=160"
}

###
GET http://localhost:8000/post


###

POST http://localhost:8000/post
Content-Type: application/json

{
    "postText": "sample post msg",
    "createdAt": "12345",
    "createdBy": "66b559370714b090abdd3913",
    "imageUrl": "sample url"
}

###

PUT  http://localhost:8000/post/like/66b93f73ad58b07e739976c5
Content-Type: application/json

{
    "userId": "66b559370714b090abdd3913",
    "isLike": true
}


###

POST http://localhost:8000/comment
Content-Type: application/json 

{
    "post": "66b93f73ad58b07e739976c5",
    "commentText": "Wow very inspiring!",
    "createdBy": "66b559370714b090abdd3913",
    "createdAt": "12345"
}


###

DELETE http://localhost:8000/comment/66bd1fe6a7865ed1b5c0b152


###

POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "name": "Test user 3",
    "email": "Test@test.com 3",
    "image": "Test image 3"
}