GET http://localhost:8000/user

###
GET http://localhost:8000/user/abhinavkrish213@gmail.com

###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name": "Test user",
    "email": "Test@test.com",
    "image": "Test image"
}

###
GET http://localhost:8000/post


###

POST http://localhost:8000/post
Content-Type: application/json

{
    "postText": "sample post msg",
    "createdAt": "12345",
    "createdBy": "66b559370714b090abdd3913",
    "imageUrl": "sample url"
}

###

PUT  http://localhost:8000/post/like/66b93f73ad58b07e739976c5
Content-Type: application/json

{
    "userId": "66b559370714b090abdd3913",
    "isLike": true
}


###

POST http://localhost:8000/comment
Content-Type: application/json 

{
    "post": "66b93f73ad58b07e739976c5",
    "commentText": "Wow very inspiring!",
    "createdBy": "66b559370714b090abdd3913",
    "createdAt": "12345"
}
