"use client";
import { Toaster } from '@/components/ui/toaster';
import { ClerkProvider } from '@clerk/nextjs'
import { Outfit } from 'next/font/google'
import { useState } from 'react'
import './globals.css'
import { UserDetailContext } from './_context/UserDetailContext'


const inter = Outfit({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [userDetail, setUserDetail] = useState();
  return (
    <ClerkProvider>
      <UserDetailContext.Provider value={{userDetail, setUserDetail}}>
    <html lang="en">
      <body className={inter.className} >{children}
        <Toaster/>
      </body>
    </html>
    </UserDetailContext.Provider>
    </ClerkProvider>
  )
}
